### PR TITLE
[spectec] Fix prose title of if instruction

### LINKED ISSUE #2151: [spec] Missing `else` from `if` instruction in title
In section "Execution > Instructions > Control Instructions", the title for the `if` instruction ([here](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-if-mathit-bt-xref-syntax-instructions-syntax-instr-mathit-instr-1-ast-xref-syntax-instructions-syntax-instr-mathit-instr-2-ast)) is rendered as `if bt instr_1* instr_2*`, so an `else` is missing between `instr_1*` and `instr_2*`.

### PR DESCRIPTION
**Pull request by f52985**
Fixes #2151.

Previously, the `RuleA` algorithm used `atom` to render the title, which caused loss of information. It now uses `mixop` instead, preserving the full information and allowing the `else` atom to be rendered correctly.

### CODE REVIEW

File: spectec/src/backend-prose/render.ml [hunk 1]
```diff
@@ -1483,20 +1483,22 @@ and render_instrs env algoname depth instrs =
...
-    | Atom.Atom s -> Atom.Atom (String.uppercase_ascii s)
-    | _ -> name.it
+let render_mixop_title env mixop params =
+  let head = Mixop.head mixop in
+  (* HARDCODE: Tweak for these instructinos *)
+  let mixop =
+    match head with
+    | Some atom ->
+      (match atom.it with
+      | Atom ("LABEL_" | "FRAME_" | "HANDLER_") -> Mixop.Atom atom
```
Comment (rossberg) [inline spectec/src/backend-prose/render.ml:1493]: Out of curiosity: why is this special case needed?

**Review by rossberg — APPROVED** [review]
Thanks!

File: spectec/src/backend-prose/render.ml (hunk 1 above)
Comment (f52985) [reply spectec/src/backend-prose/render.ml:1493]: Oh, that's because the algorithms (`RuleA`) for these context instructions do not have parameters, and the `tails` of the mixop should be dropped to match the arity.
